# Generated by Django 5.1.2 on 2025-11-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
