# Generated by Django 5.1.2 on 2025-11-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remote_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
