# Generated by Django 5.1.2 on 2025-11-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_remote_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='remote_image_url',
            new_name='image_url',
        ),
    ]
