# Generated by Django 5.1.2 on 2025-11-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_fix_banknifty_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
