# Generated by Django 5.1.2 on 2025-11-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_seed_more_products'),
    ]

    operations = [
    ]
